---
version: 1
kind: group
logging:
  level: DEBUG
framework: tensorflow
build:
  backend: native
  image: 'tensorflow/tensorflow:1.4.1-py3'
  build_steps:
    - pip install polyaxon-client
    - pip install boto3
    - pip install botocore
hptuning:
  concurrency: 4
  # random_search:
  #   n_experiments: 2
  matrix:
    learning_rate:
      linspace: '0.001:0.1:2'
    activation:
      values:
        - relu
        - sigmoid
    # dropout:
    #   values: [0.25, 0.3]
params:
  batch_size: 128
  num_steps: 500
  num_epochs: 1
run:
  cmd:  python model.py --batch_size={{ batch_size }} \
                        --num_steps={{ num_steps }} \
                        --learning_rate={{ learning_rate }} \
                        --num_epochs={{ num_epochs }} \
                        --activation={{ activation }}
